-- MySQL Script generated by MySQL Workbench
-- Fri Jan 15 17:03:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`profile_picture_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profile_picture_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `picture_path` VARCHAR(245) NULL,
  `size` INT NULL,
  `extension` VARCHAR(45) NULL,
  `creatAt` DATETIME NULL,
  `updateAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profile_cover_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profile_cover_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `picture_path` VARCHAR(245) NULL,
  `size` INT NULL,
  `extension` VARCHAR(45) NULL,
  `creatAt` DATETIME NULL,
  `updateAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `roles` JSON NULL,
  `password` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `birthdate` DATE NULL,
  `bio` VARCHAR(245) NULL,
  `location` VARCHAR(45) NULL,
  `creatAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `profile_picture_user_id` INT NOT NULL,
  `profile_cover_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `firstname_UNIQUE` (`firstname` ASC) VISIBLE,
  INDEX `fk_user_profile_picture_user_idx` (`profile_picture_user_id` ASC) VISIBLE,
  INDEX `fk_user_profile_cover_user1_idx` (`profile_cover_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_profile_picture_user`
    FOREIGN KEY (`profile_picture_user_id`)
    REFERENCES `mydb`.`profile_picture_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_profile_cover_user1`
    FOREIGN KEY (`profile_cover_user_id`)
    REFERENCES `mydb`.`profile_cover_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body` VARCHAR(245) NULL,
  `picture_path` VARCHAR(245) NULL,
  `size` INT NULL,
  `extension` VARCHAR(45) NULL,
  `createAt` DATETIME NULL,
  `updateAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body` VARCHAR(245) NULL,
  `posts_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_posts1_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_comments_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `mydb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `media_path` VARCHAR(245) NULL,
  `size` INT NULL,
  `extension` VARCHAR(45) NULL,
  `createAt` DATETIME NULL,
  `updateAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` DATETIME NULL,
  `posts_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_posts1_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_likes_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `mydb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`repost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`repost` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createAt` DATETIME NULL,
  `posts_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repost_posts1_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_repost_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_repost_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `mydb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repost_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`followers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enabled` TINYINT NULL,
  `abonné` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media_user_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media_user_has_user` (
  `media_user_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`media_user_id`, `user_id`),
  INDEX `fk_media_user_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_media_user_has_user_media_user1_idx` (`media_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_media_user_has_user_media_user1`
    FOREIGN KEY (`media_user_id`)
    REFERENCES `mydb`.`media_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_user_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_posts` (
  `user_id` INT NOT NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `posts_id`),
  INDEX `fk_user_has_posts_posts1_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_user_has_posts_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_posts_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_posts_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `mydb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_followers` (
  `user_id` INT NOT NULL,
  `followers_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `followers_id`),
  INDEX `fk_user_has_followers_followers1_idx` (`followers_id` ASC) VISIBLE,
  INDEX `fk_user_has_followers_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_followers_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_followers_followers1`
    FOREIGN KEY (`followers_id`)
    REFERENCES `mydb`.`followers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
