<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6vixmNo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6vixmNo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6vixmNo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6vixmNo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6vixmNo\App_KernelDevDebugContainer([
    'container.build_hash' => '6vixmNo',
    'container.build_id' => 'eec5b5f2',
    'container.build_time' => 1608424200,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6vixmNo');
