<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDtj7u5R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDtj7u5R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDtj7u5R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDtj7u5R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDtj7u5R\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dtj7u5R',
    'container.build_id' => 'fcaca0a4',
    'container.build_time' => 1608333860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDtj7u5R');
